#!/bin/sh

# swap mouse buttons
#xmodmap -e 'pointer = 3 2 1'

# turn caps lock key into a control key
# (not needed because the keymap file specifies this already)
# setxkbmap -option ctrl:nocaps

# load xkb extensions
xkbcomp -I$HOME/.xkb ~/.xkb/keymap/cantora $DISPLAY

# key repeat rate: after 200 ms, repeat at 30 hz
xset r rate 200 30

export _JAVA_AWT_WM_NONREPARENTING=1

[[ -f "$HOME/.Xmodmap" ]] && xmodmap "$HOME/.Xmodmap"  

